services:
  api:
    build: ./
    ports:
      - 8000:8000
    environment:
      - PYTHONBUFFERED=1
      - DATABASE_URL=db
      - SERVER_PORT=8000
    entrypoint: ./entrypoint.sh
    expose:
      - "8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mobilab
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d mobilab" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

