# Generated by Django 4.0.3 on 2022-03-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('balance', models.FloatField(default=0)),
                ('closed', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='John', max_length=100)),
                ('phone', models.CharField(default='0000', max_length=100)),
                ('email', models.CharField(default='def@ault.default', max_length=100)),
                ('register_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
