# Generated by Django 4.0.3 on 2022-04-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_remove_transaction_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='0 EUR', max_length=250),
        ),
    ]
