# Generated by Django 4.0.3 on 2022-04-02 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_transactionextra_transaction_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionextra',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extra', serialize=False, to='bank.transaction'),
        ),
    ]
