# Generated by Django 4.0.3 on 2022-04-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_alter_transactionextra_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcustomer',
            name='address',
            field=models.CharField(default='Simple Address', max_length=250),
        ),
    ]
