# Generated by Django 4.0.3 on 2022-04-02 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_bankcustomer_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['created']},
        ),
    ]
