# Generated by Django 4.0.3 on 2022-04-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcustomer',
            name='address',
            field=models.CharField(default='Simple Address, Simple Block', max_length=250),
        ),
        migrations.AlterField(
            model_name='bankcustomer',
            name='name',
            field=models.CharField(default='John Murray', max_length=100),
        ),
        migrations.AlterField(
            model_name='bankcustomer',
            name='phone',
            field=models.CharField(default='+12345678', max_length=100),
        ),
    ]
