# Generated by Django 4.0.3 on 2022-04-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_alter_bankcustomer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_name',
            field=models.CharField(default='A simple account', max_length=100),
        ),
    ]
