name: Mobilab Application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [ "3.10" ]
    env:
      DEFAULT_DB: github
    steps:
      - uses: actions/checkout@v3
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'
          postgresql db: mobilab
          postgresql user: postgres
          postgresql password: postgres

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Migrate data
        run: |
          python manage.py migrate

      - name: test
        run: |
          python manage.py test bank
